export const documentedPresentationFixture = {
  fixtureId: "demo-event-1",
  fixtureLabel: "Contoh presentasi dari dokumen kontrak; bukan respons API",
  sourceRecord: "docs/contracts.examples.json, schema 2.0",
  openApiHistoryNote: "Contoh EventPage riwayat pada OpenAPI memiliki data: [].",
  event: {
    id: "demo-event-1",
    version: 1,
    title: "Bus 12 diversion (synthetic demo)",
    summary: "Synthetic, non-live example of a service diversion.",
    category: "transport_road_incidents",
    lifecycle: "ongoing",
    freshness: {
      status: "current",
      evaluatedAt: "2026-09-24T09:00:00+07:00",
      reviewDueAt: "2026-09-24T09:30:00+07:00",
      basis: "source_validity",
    },
    eventTime: {
      start: "2026-09-24T08:00:00+07:00",
      end: null,
      precision: "exact",
    },
    validity: {
      validFrom: "2026-09-24T08:00:00+07:00",
      validUntil: "2026-09-24T10:00:00+07:00",
    },
    publishedAt: "2026-09-24T09:00:00+07:00",
  },
  claim: {
    id: "demo-claim-1",
    text: "Synthetic demo: Operator 12 announces Bus 12 diversion on Jalan Contoh on 2026-09-24 08:00 WIB.",
    qualifier: "Synthetic example; not a live road warning.",
    evidenceLabel: "issuer_notice",
    sourceSupport: "supports",
    contraryEvidenceCount: 0,
    originId: "demo-origin-1",
  },
  source: {
    sourceId: "demo-source-operator-12",
    displayName: "Synthetic Transit Operator",
    url: "https://example.invalid/demo/bus-diversion",
    reportRevisionId: "demo-report-r1",
    publishedAt: "2026-09-24T09:00:00+07:00",
    observedAt: null,
    retrievedAt: "2026-09-24T09:00:00+07:00",
    validFrom: "2026-09-24T08:00:00+07:00",
    validUntil: "2026-09-24T10:00:00+07:00",
    permittedText: "Synthetic demo: Operator 12 announces Bus 12 diversion on Jalan Contoh on 2026-09-24 08:00 WIB.",
    contentHash: "c97d7e50c98b2ac807c6b8928c14332734e8e9bae45d53a3e7bedafcad49422a",
    evidenceSpan: {
      start: 0,
      end: 95,
      offsetUnit: "unicode_code_points",
      relation: "supports",
    },
  },
  origin: {
    id: "demo-origin-1",
    kind: "operator_notice",
    actorLabel: "Synthetic Transit Operator",
    lineageRelation: "original",
    independenceStatus: "established",
    dependsOnOriginIds: [],
  },
  geometry: {
    id: "demo-geometry-route",
    role: "route_segment",
    displayLabel: "Jalan Contoh (synthetic)",
    type: "LineString",
    coordinates: [
      [106.8, -6.2],
      [106.81, -6.21],
    ],
    coordinateReferenceSystem: "OGC:CRS84",
    precisionMeters: null,
    precisionBasis: "unknown",
  },
  impact: {
    id: "demo-impact-1",
    title: "Bus 12 detour",
    description: "Synthetic route effect example.",
    type: "traffic_diversion",
  },
  publicationDecision: {
    id: "demo-decision-1",
    status: "published",
    reviewerId: "demo-moderator-1",
    decidedAt: "2026-09-24T09:00:00+07:00",
    reasonCode: "reviewed_synthetic_fixture",
  },
  history: [] as const,
} as const;

export type DocumentedPresentationFixture = typeof documentedPresentationFixture;
